/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.53
 * Generated at: 2018-10-05 02:59:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    <!DOCTYPE html>\r\n");
      out.write("    <html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("    \r\n");
      out.write("\t<title>Insert title here</title>\r\n");
      out.write("      <style media=\"screen\">\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      /*//////////////////////////////////////////////////////////////////\r\n");
      out.write("      [ FONT ]*/\r\n");
      out.write("      \r\n");
      out.write("      @font-face {\r\n");
      out.write("        font-family: Poppins-Regular;\r\n");
      out.write("        src: url('../fonts/poppins/Poppins-Regular.ttf'); \r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      @font-face {\r\n");
      out.write("        font-family: Poppins-Medium;\r\n");
      out.write("        src: url('../fonts/poppins/Poppins-Medium.ttf'); \r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      @font-face {\r\n");
      out.write("        font-family: Poppins-Bold;\r\n");
      out.write("        src: url('../fonts/poppins/Poppins-Bold.ttf'); \r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      @font-face {\r\n");
      out.write("        font-family: Poppins-SemiBold;\r\n");
      out.write("        src: url('../fonts/poppins/Poppins-SemiBold.ttf'); \r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      /*//////////////////////////////////////////////////////////////////\r\n");
      out.write("      [ RESTYLE TAG ]*/\r\n");
      out.write("      \r\n");
      out.write("      * {\r\n");
      out.write("        margin: 0px; \r\n");
      out.write("        padding: 0px; \r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      body, html {\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        font-family: Poppins-Regular, sans-serif;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      /*---------------------------------------------*/\r\n");
      out.write("      a {\r\n");
      out.write("        font-family: Poppins-Regular;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        line-height: 1.7;\r\n");
      out.write("        color: #666666;\r\n");
      out.write("        margin: 0px;\r\n");
      out.write("        transition: all 0.4s;\r\n");
      out.write("        -webkit-transition: all 0.4s;\r\n");
      out.write("        -o-transition: all 0.4s;\r\n");
      out.write("        -moz-transition: all 0.4s;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      a:focus {\r\n");
      out.write("        outline: none !important;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      a:hover {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: #a64bf4;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      /*---------------------------------------------*/\r\n");
      out.write("      h1,h2,h3,h4,h5,h6 {\r\n");
      out.write("        margin: 0px;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      p {\r\n");
      out.write("        font-family: Poppins-Regular;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        line-height: 1.7;\r\n");
      out.write("        color: #666666;\r\n");
      out.write("        margin: 0px;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      ul, li {\r\n");
      out.write("        margin: 0px;\r\n");
      out.write("        list-style-type: none;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      /*---------------------------------------------*/\r\n");
      out.write("      input {\r\n");
      out.write("        outline: none;\r\n");
      out.write("        border: none;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      textarea {\r\n");
      out.write("        outline: none;\r\n");
      out.write("        border: none;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      textarea:focus, input:focus {\r\n");
      out.write("        border-color: transparent !important;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      input:focus::-webkit-input-placeholder { color:transparent; }\r\n");
      out.write("      input:focus:-moz-placeholder { color:transparent; }\r\n");
      out.write("      input:focus::-moz-placeholder { color:transparent; }\r\n");
      out.write("      input:focus:-ms-input-placeholder { color:transparent; }\r\n");
      out.write("      \r\n");
      out.write("      textarea:focus::-webkit-input-placeholder { color:transparent; }\r\n");
      out.write("      textarea:focus:-moz-placeholder { color:transparent; }\r\n");
      out.write("      textarea:focus::-moz-placeholder { color:transparent; }\r\n");
      out.write("      textarea:focus:-ms-input-placeholder { color:transparent; }\r\n");
      out.write("      \r\n");
      out.write("      input::-webkit-input-placeholder { color: #adadad;}\r\n");
      out.write("      input:-moz-placeholder { color: #adadad;}\r\n");
      out.write("      input::-moz-placeholder { color: #adadad;}\r\n");
      out.write("      input:-ms-input-placeholder { color: #adadad;}\r\n");
      out.write("      \r\n");
      out.write("      textarea::-webkit-input-placeholder { color: #adadad;}\r\n");
      out.write("      textarea:-moz-placeholder { color: #adadad;}\r\n");
      out.write("      textarea::-moz-placeholder { color: #adadad;}\r\n");
      out.write("      textarea:-ms-input-placeholder { color: #adadad;}\r\n");
      out.write("      \r\n");
      out.write("      /*---------------------------------------------*/\r\n");
      out.write("      button {\r\n");
      out.write("        outline: none !important;\r\n");
      out.write("        border: none;\r\n");
      out.write("        background: transparent;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      button:hover {\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      iframe {\r\n");
      out.write("        border: none !important;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      /*//////////////////////////////////////////////////////////////////\r\n");
      out.write("      [ Utility ]*/\r\n");
      out.write("      .txt1 {\r\n");
      out.write("        font-family: Poppins-Regular;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        line-height: 1.5;\r\n");
      out.write("        color: #666666;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .txt2 {\r\n");
      out.write("        font-family: Poppins-Regular;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        line-height: 1.5;\r\n");
      out.write("        color: #333333;\r\n");
      out.write("        text-transform: uppercase;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .bg1 {background-color: #3b5998}\r\n");
      out.write("      .bg2 {background-color: #1da1f2}\r\n");
      out.write("      .bg3 {background-color: #ea4335}\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      /*//////////////////////////////////////////////////////////////////\r\n");
      out.write("      [ login ]*/\r\n");
      out.write("      .limiter {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .container-login100 {\r\n");
      out.write("        width: 100%;  \r\n");
      out.write("        min-height: 100vh;\r\n");
      out.write("        display: -webkit-box;\r\n");
      out.write("        display: -webkit-flex;\r\n");
      out.write("        display: -moz-box;\r\n");
      out.write("        display: -ms-flexbox;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-wrap: wrap;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        padding: 15px;\r\n");
      out.write("        background-repeat: no-repeat;\r\n");
      out.write("        background-position: center;\r\n");
      out.write("        background-size: cover;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .wrap-login100 {\r\n");
      out.write("        width: 500px;\r\n");
      out.write("        background: #fff;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      /*------------------------------------------------------------------\r\n");
      out.write("      [ Form ]*/\r\n");
      out.write("      \r\n");
      out.write("      .login100-form {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .login100-form-title {\r\n");
      out.write("        display: block;\r\n");
      out.write("        font-family: Poppins-Bold;\r\n");
      out.write("        font-size: 39px;\r\n");
      out.write("        color: #333333;\r\n");
      out.write("        line-height: 1.2;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      /*------------------------------------------------------------------\r\n");
      out.write("      [ Input ]*/\r\n");
      out.write("      \r\n");
      out.write("      .wrap-input100 {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        border-bottom: 2px solid #d9d9d9;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .label-input100 {\r\n");
      out.write("        font-family: Poppins-Regular;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("        color: #333333;\r\n");
      out.write("        line-height: 1.5;\r\n");
      out.write("        padding-left: 7px;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .input100 {\r\n");
      out.write("        font-family: Poppins-Medium;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        color: #333333;\r\n");
      out.write("        line-height: 1.2;\r\n");
      out.write("      \r\n");
      out.write("        display: block;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 55px;\r\n");
      out.write("        background: transparent;\r\n");
      out.write("        padding: 0 7px 0 43px;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      /*---------------------------------------------*/\r\n");
      out.write("      .focus-input100 {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        display: block;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        pointer-events: none;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .focus-input100::after {\r\n");
      out.write("        content: attr(data-symbol);\r\n");
      out.write("        font-family: Material-Design-Iconic-Font;\r\n");
      out.write("        color: #adadad;\r\n");
      out.write("        font-size: 22px;\r\n");
      out.write("      \r\n");
      out.write("        display: -webkit-box;\r\n");
      out.write("        display: -webkit-flex;\r\n");
      out.write("        display: -moz-box;\r\n");
      out.write("        display: -ms-flexbox;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        height: calc(100% - 20px);\r\n");
      out.write("        bottom: 0;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        padding-left: 13px;\r\n");
      out.write("        padding-top: 3px;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .focus-input100::before {\r\n");
      out.write("        content: \"\";\r\n");
      out.write("        display: block;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        bottom: -2px;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        width: 0;\r\n");
      out.write("        height: 2px;\r\n");
      out.write("        background: #7f7f7f;\r\n");
      out.write("        -webkit-transition: all 0.4s;\r\n");
      out.write("        -o-transition: all 0.4s;\r\n");
      out.write("        -moz-transition: all 0.4s;\r\n");
      out.write("        transition: all 0.4s;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      .input100:focus + .focus-input100::before {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .has-val.input100 + .focus-input100::before {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .input100:focus + .focus-input100::after {\r\n");
      out.write("        color: #a64bf4;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .has-val.input100 + .focus-input100::after {\r\n");
      out.write("        color: #a64bf4;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      /*------------------------------------------------------------------\r\n");
      out.write("      [ Button ]*/\r\n");
      out.write("      .container-login100-form-btn {\r\n");
      out.write("        display: -webkit-box;\r\n");
      out.write("        display: -webkit-flex;\r\n");
      out.write("        display: -moz-box;\r\n");
      out.write("        display: -ms-flexbox;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-wrap: wrap;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .wrap-login100-form-btn {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        display: block;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        z-index: 1;\r\n");
      out.write("        border-radius: 25px;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("      \r\n");
      out.write("        box-shadow: 0 5px 30px 0px rgba(3, 216, 222, 0.2);\r\n");
      out.write("        -moz-box-shadow: 0 5px 30px 0px rgba(3, 216, 222, 0.2);\r\n");
      out.write("        -webkit-box-shadow: 0 5px 30px 0px rgba(3, 216, 222, 0.2);\r\n");
      out.write("        -o-box-shadow: 0 5px 30px 0px rgba(3, 216, 222, 0.2);\r\n");
      out.write("        -ms-box-shadow: 0 5px 30px 0px rgba(3, 216, 222, 0.2);\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .login100-form-bgbtn {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        z-index: -1;\r\n");
      out.write("        width: 300%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        background: #a64bf4;\r\n");
      out.write("        background: -webkit-linear-gradient(right, #00dbde, #fc00ff, #00dbde, #fc00ff);\r\n");
      out.write("        background: -o-linear-gradient(right, #00dbde, #fc00ff, #00dbde, #fc00ff);\r\n");
      out.write("        background: -moz-linear-gradient(right, #00dbde, #fc00ff, #00dbde, #fc00ff);\r\n");
      out.write("        background: linear-gradient(right, #00dbde, #fc00ff, #00dbde, #fc00ff);\r\n");
      out.write("        top: 0;\r\n");
      out.write("        left: -100%;\r\n");
      out.write("      \r\n");
      out.write("        -webkit-transition: all 0.4s;\r\n");
      out.write("        -o-transition: all 0.4s;\r\n");
      out.write("        -moz-transition: all 0.4s;\r\n");
      out.write("        transition: all 0.4s;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .login100-form-btn {\r\n");
      out.write("        font-family: Poppins-Medium;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        line-height: 1.2;\r\n");
      out.write("        text-transform: uppercase;\r\n");
      out.write("      \r\n");
      out.write("        display: -webkit-box;\r\n");
      out.write("        display: -webkit-flex;\r\n");
      out.write("        display: -moz-box;\r\n");
      out.write("        display: -ms-flexbox;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        padding: 0 20px;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 50px;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .wrap-login100-form-btn:hover .login100-form-bgbtn {\r\n");
      out.write("        left: 0;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      /*------------------------------------------------------------------\r\n");
      out.write("      [ Alert validate ]*/\r\n");
      out.write("      \r\n");
      out.write("      .validate-input {\r\n");
      out.write("        position: relative;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .alert-validate::before {\r\n");
      out.write("        content: attr(data-validate);\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        max-width: 70%;\r\n");
      out.write("        background-color: #fff;\r\n");
      out.write("        border: 1px solid #c80000;\r\n");
      out.write("        border-radius: 2px;\r\n");
      out.write("        padding: 4px 25px 4px 10px;\r\n");
      out.write("        bottom: calc((100% - 20px) / 2);\r\n");
      out.write("        -webkit-transform: translateY(50%);\r\n");
      out.write("        -moz-transform: translateY(50%);\r\n");
      out.write("        -ms-transform: translateY(50%);\r\n");
      out.write("        -o-transform: translateY(50%);\r\n");
      out.write("        transform: translateY(50%);\r\n");
      out.write("        right: 2px;\r\n");
      out.write("        pointer-events: none;\r\n");
      out.write("      \r\n");
      out.write("        font-family: Poppins-Regular;\r\n");
      out.write("        color: #c80000;\r\n");
      out.write("        font-size: 13px;\r\n");
      out.write("        line-height: 1.4;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("      \r\n");
      out.write("        visibility: hidden;\r\n");
      out.write("        opacity: 0;\r\n");
      out.write("      \r\n");
      out.write("        -webkit-transition: opacity 0.4s;\r\n");
      out.write("        -o-transition: opacity 0.4s;\r\n");
      out.write("        -moz-transition: opacity 0.4s;\r\n");
      out.write("        transition: opacity 0.4s;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .alert-validate::after {\r\n");
      out.write("        content: \"\\f06a\";\r\n");
      out.write("        font-family: FontAwesome;\r\n");
      out.write("        display: block;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        color: #c80000;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        bottom: calc((100% - 20px) / 2);\r\n");
      out.write("        -webkit-transform: translateY(50%);\r\n");
      out.write("        -moz-transform: translateY(50%);\r\n");
      out.write("        -ms-transform: translateY(50%);\r\n");
      out.write("        -o-transform: translateY(50%);\r\n");
      out.write("        transform: translateY(50%);\r\n");
      out.write("        right: 8px;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .alert-validate:hover:before {\r\n");
      out.write("        visibility: visible;\r\n");
      out.write("        opacity: 1;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      @media (max-width: 992px) {\r\n");
      out.write("        .alert-validate::before {\r\n");
      out.write("          visibility: visible;\r\n");
      out.write("          opacity: 1;\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      /*//////////////////////////////////////////////////////////////////\r\n");
      out.write("      [ Social item ]*/\r\n");
      out.write("      .login100-social-item {\r\n");
      out.write("        font-size: 25px;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("      \r\n");
      out.write("        display: -webkit-box;\r\n");
      out.write("        display: -webkit-flex;\r\n");
      out.write("        display: -moz-box;\r\n");
      out.write("        display: -ms-flexbox;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        width: 50px;\r\n");
      out.write("        height: 50px;\r\n");
      out.write("        border-radius: 50%;\r\n");
      out.write("        margin: 5px;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      .login100-social-item:hover {\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        background-color: #333333;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      /*//////////////////////////////////////////////////////////////////\r\n");
      out.write("      [ Responsive ]*/\r\n");
      out.write("      \r\n");
      out.write("      @media (max-width: 576px) {\r\n");
      out.write("        .wrap-login100 {\r\n");
      out.write("          padding-left: 15px;\r\n");
      out.write("          padding-right: 15px;\r\n");
      out.write("        }\r\n");
      out.write("      } \r\n");
      out.write("      </style>\r\n");
      out.write("      \r\n");
      out.write("    \t<meta charset=\"UTF-8\">\r\n");
      out.write("    \t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <!--===============================================================================================-->\t\r\n");
      out.write("    \t<link rel=\"icon\" type=\"image/png\" href=\"images/icons/favicon.ico\"/>\r\n");
      out.write("    <!--===============================================================================================-->\r\n");
      out.write("    \t<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("    <!--===============================================================================================-->\r\n");
      out.write("    \t<link rel=\"stylesheet\" type=\"text/css\" href=\"fonts/font-awesome-4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("    <!--===============================================================================================-->\r\n");
      out.write("    \t<link rel=\"stylesheet\" type=\"text/css\" href=\"fonts/iconic/css/material-design-iconic-font.min.css\">\r\n");
      out.write("    <!--===============================================================================================-->\r\n");
      out.write("    \t<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/animate/animate.css\">\r\n");
      out.write("    <!--===============================================================================================-->\t\r\n");
      out.write("    \t<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/css-hamburgers/hamburgers.min.css\">\r\n");
      out.write("    <!--===============================================================================================-->\r\n");
      out.write("    \t<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/animsition/css/animsition.min.css\">\r\n");
      out.write("    <!--===============================================================================================-->\r\n");
      out.write("    \t<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/select2/select2.min.css\">\r\n");
      out.write("    <!--===============================================================================================-->\t\r\n");
      out.write("    \t<link rel=\"stylesheet\" type=\"text/css\" href=\"vendor/daterangepicker/daterangepicker.css\">\r\n");
      out.write("    <!--===============================================================================================-->\r\n");
      out.write("    \t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/util.css\">\r\n");
      out.write("    \t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\">\r\n");
      out.write("    <!--===============================================================================================-->\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("    \t<h5>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("    \t<div class=\"limiter\">\r\n");
      out.write("    \t\t<div class=\"container-login100\" style=\"background-image: url('images/bg-01.jpg');\">\r\n");
      out.write("    \t\t\t<div class=\"wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54\">\r\n");
      out.write("    \t\t\t\t<form class=\"login100-form validate-form\" method=\"post\">\r\n");
      out.write("    \t\t\t\t\t<span class=\"login100-form-title p-b-49\">\r\n");
      out.write("    \t\t\t\t\t\tLogin\r\n");
      out.write("    \t\t\t\t\t</span>\r\n");
      out.write("    \r\n");
      out.write("    \t\t\t\t\t<div class=\"wrap-input100 validate-input m-b-23\" data-validate = \"Username is reauired\">\r\n");
      out.write("    \t\t\t\t\t\t<span class=\"label-input100\">Username</span>\r\n");
      out.write("    \t\t\t\t\t\t<input class=\"input100\" type=\"text\" name=\"id\" placeholder=\"id\">\r\n");
      out.write("    \t\t\t\t\t\t<span class=\"focus-input100\" data-symbol=\"&#xf206;\"></span>\r\n");
      out.write("    \t\t\t\t\t</div>\r\n");
      out.write("    \r\n");
      out.write("    \t\t\t\t\t<div class=\"wrap-input100 validate-input\" data-validate=\"Password is required\">\r\n");
      out.write("    \t\t\t\t\t\t<span class=\"label-input100\">Password</span>\r\n");
      out.write("    \t\t\t\t\t\t<input class=\"input100\" type=\"password\" name=\"pw\" placeholder=\"password\">\r\n");
      out.write("    \t\t\t\t\t\t<span class=\"focus-input100\" data-symbol=\"&#xf190;\"></span>\r\n");
      out.write("    \t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\r\n");
      out.write("    \t\t\t\t\t<div class=\"text-right p-t-8 p-b-31\">\r\n");
      out.write("    \t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("    \t\t\t\t\t\t\tForgot password?\r\n");
      out.write("    \t\t\t\t\t\t</a>\r\n");
      out.write("    \t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\r\n");
      out.write("    \t\t\t\t\t<div class=\"container-login100-form-btn\">\r\n");
      out.write("    \t\t\t\t\t\t<div class=\"wrap-login100-form-btn\">\r\n");
      out.write("    \t\t\t\t\t\t\t<div class=\"login100-form-bgbtn\"></div>\r\n");
      out.write("    \t\t\t\t\t\t\t<button type=\"submit\" class=\"login100-form-btn\">\r\n");
      out.write("    \t\t\t\t\t\t\t\tLogin\r\n");
      out.write("    \t\t\t\t\t\t\t</button>\r\n");
      out.write("    \t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t</div>\r\n");
      out.write("    \r\n");
      out.write("    \t\t\t\t\t<div class=\"txt1 text-center p-t-54 p-b-20\">\r\n");
      out.write("    \t\t\t\t\t\t<span>\r\n");
      out.write("    \t\t\t\t\t\t\tOr Sign Up Using\r\n");
      out.write("    \t\t\t\t\t\t</span>\r\n");
      out.write("    \t\t\t\t\t</div>\r\n");
      out.write("    \r\n");
      out.write("    \t\t\t\t\t<div class=\"flex-c-m\">\r\n");
      out.write("    \t\t\t\t\t\t<a href=\"#\" class=\"login100-social-item bg1\">\r\n");
      out.write("    \t\t\t\t\t\t\t<i class=\"fa fa-facebook\"></i>\r\n");
      out.write("    \t\t\t\t\t\t</a>\r\n");
      out.write("    \r\n");
      out.write("    \t\t\t\t\t\t<a href=\"#\" class=\"login100-social-item bg2\">\r\n");
      out.write("    \t\t\t\t\t\t\t<i class=\"fa fa-twitter\"></i>\r\n");
      out.write("    \t\t\t\t\t\t</a>\r\n");
      out.write("    \r\n");
      out.write("    \t\t\t\t\t\t<a href=\"#\" class=\"login100-social-item bg3\">\r\n");
      out.write("    \t\t\t\t\t\t\t<i class=\"fa fa-google\"></i>\r\n");
      out.write("    \t\t\t\t\t\t</a>\r\n");
      out.write("    \t\t\t\t\t</div>\r\n");
      out.write("    \r\n");
      out.write("    \t\t\t\t\t<div class=\"flex-col-c p-t-155\">\r\n");
      out.write("    \t\t\t\t\t\t<span class=\"txt1 p-b-17\">\r\n");
      out.write("    \t\t\t\t\t\t\tOr Sign Up Using\r\n");
      out.write("    \t\t\t\t\t\t</span>\r\n");
      out.write("    \r\n");
      out.write("    \t\t\t\t\t\t<a href=\"#\" class=\"txt2\">\r\n");
      out.write("    \t\t\t\t\t\t\tSign Up\r\n");
      out.write("    \t\t\t\t\t\t</a>\r\n");
      out.write("    \t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t</form>\r\n");
      out.write("    \t\t\t</div>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t\r\n");
      out.write("    \r\n");
      out.write("    \t<div id=\"dropDownSelect1\"></div>\r\n");
      out.write("    \t\r\n");
      out.write("    <!--===============================================================================================-->\r\n");
      out.write("    \t<script src=\"vendor/jquery/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("    <!--===============================================================================================-->\r\n");
      out.write("    \t<script src=\"vendor/animsition/js/animsition.min.js\"></script>\r\n");
      out.write("    <!--===============================================================================================-->\r\n");
      out.write("    \t<script src=\"vendor/bootstrap/js/popper.js\"></script>\r\n");
      out.write("    \t<script src=\"vendor/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!--===============================================================================================-->\r\n");
      out.write("    \t<script src=\"vendor/select2/select2.min.js\"></script>\r\n");
      out.write("    <!--===============================================================================================-->\r\n");
      out.write("    \t<script src=\"vendor/daterangepicker/moment.min.js\"></script>\r\n");
      out.write("    \t<script src=\"vendor/daterangepicker/daterangepicker.js\"></script>\r\n");
      out.write("    <!--===============================================================================================-->\r\n");
      out.write("    \t<script src=\"vendor/countdowntime/countdowntime.js\"></script>\r\n");
      out.write("    <!--===============================================================================================-->\r\n");
      out.write("    \t<script src=\"js/main.js\">\r\n");
      out.write("      \r\n");
      out.write("      (function ($) {\r\n");
      out.write("          \"use strict\";\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("           /*==================================================================\r\n");
      out.write("          [ Focus input ]*/\r\n");
      out.write("          $('.input100').each(function(){\r\n");
      out.write("              $(this).on('blur', function(){\r\n");
      out.write("                  if($(this).val().trim() != \"\") {\r\n");
      out.write("                      $(this).addClass('has-val');\r\n");
      out.write("                  }\r\n");
      out.write("                  else {\r\n");
      out.write("                      $(this).removeClass('has-val');\r\n");
      out.write("                  }\r\n");
      out.write("              })    \r\n");
      out.write("          })\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("          /*==================================================================\r\n");
      out.write("          [ Validate ]*/\r\n");
      out.write("          var input = $('.validate-input .input100');\r\n");
      out.write("      \r\n");
      out.write("          $('.validate-form').on('submit',function(){\r\n");
      out.write("              var check = true;\r\n");
      out.write("      \r\n");
      out.write("              for(var i=0; i<input.length; i++) {\r\n");
      out.write("                  if(validate(input[i]) == false){\r\n");
      out.write("                      showValidate(input[i]);\r\n");
      out.write("                      check=false;\r\n");
      out.write("                  }\r\n");
      out.write("              }\r\n");
      out.write("      \r\n");
      out.write("              return check;\r\n");
      out.write("          });\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("          $('.validate-form .input100').each(function(){\r\n");
      out.write("              $(this).focus(function(){\r\n");
      out.write("                 hideValidate(this);\r\n");
      out.write("              });\r\n");
      out.write("          });\r\n");
      out.write("      \r\n");
      out.write("          function validate (input) {\r\n");
      out.write("              if($(input).attr('type') == 'email' || $(input).attr('name') == 'email') {\r\n");
      out.write("                  if($(input).val().trim().match(/^([a-zA-Z0-9_\\-\\.]+)@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.)|(([a-zA-Z0-9\\-]+\\.)+))([a-zA-Z]{1,5}|[0-9]{1,3})(\\]?)$/) == null) {\r\n");
      out.write("                      return false;\r\n");
      out.write("                  }\r\n");
      out.write("              }\r\n");
      out.write("              else {\r\n");
      out.write("                  if($(input).val().trim() == ''){\r\n");
      out.write("                      return false;\r\n");
      out.write("                  }\r\n");
      out.write("              }\r\n");
      out.write("          }\r\n");
      out.write("      \r\n");
      out.write("          function showValidate(input) {\r\n");
      out.write("              var thisAlert = $(input).parent();\r\n");
      out.write("      \r\n");
      out.write("              $(thisAlert).addClass('alert-validate');\r\n");
      out.write("          }\r\n");
      out.write("      \r\n");
      out.write("          function hideValidate(input) {\r\n");
      out.write("              var thisAlert = $(input).parent();\r\n");
      out.write("      \r\n");
      out.write("              $(thisAlert).removeClass('alert-validate');\r\n");
      out.write("          }\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("      \r\n");
      out.write("      })(jQuery);\r\n");
      out.write("        \r\n");
      out.write("      </script>\r\n");
      out.write("    \r\n");
      out.write("    </body>\r\n");
      out.write("    </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
